services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/generated_files:/app/generated_files
      - ./backend/uploaded_documents:/app/uploaded_documents
      - ./backend/chroma_db:/app/chroma_db
    restart: always
