"""Add is_global to documents

Revision ID: 8d567a5ba1ce
Revises: aabf346d521e
Create Date: 2026-08-07 12:07:25.923746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d567a5ba1ce'
down_revision: Union[str, Sequence[str], None] = 'aabf346d521e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_global', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'is_global')
    # ### end Alembic commands ###
