import { useState } from 'react'
import { AutoAwesomeRounded, LockOutlined, MailOutlined } from '@mui/icons-material'
import { Alert, Box, Button, CircularProgress, InputAdornment, Paper, TextField, Typography } from '@mui/material'
import { Link, useNavigate } from 'react-router-dom'
import useAuth from '../hooks/useAuth'
export default function Login() { const { login } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ email: '', password: '' }); const [error,setError] = useState(''); const [busy,setBusy] = useState(false)
 const submit = async e => { e.preventDefault(); setBusy(true); setError(''); const result = await login(form); setBusy(false); result.success ? navigate('/') : setError(result.message) }
 return <AuthShell title="Welcome back" subtitle="Sign in to continue creating with AI."><Box component="form" onSubmit={submit} sx={{ display:'grid', gap:2 }}><TextField required label="Email address" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} InputProps={{startAdornment:<InputAdornment position="start"><MailOutlined fontSize="small" /></InputAdornment>}}/><TextField required label="Password" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} InputProps={{startAdornment:<InputAdornment position="start"><LockOutlined fontSize="small" /></InputAdornment>}}/>{error && <Alert severity="error">{error}</Alert>}<Button type="submit" variant="contained" size="large" disabled={busy}>{busy ? <CircularProgress size={22} color="inherit"/> : 'Sign in'}</Button><Typography textAlign="center" fontSize={14} color="text.secondary">New here? <Link to="/register" style={{color:'#2563eb',fontWeight:700}}>Create an account</Link></Typography></Box></AuthShell> }
export function AuthShell({ title, subtitle, children }) { return <Box sx={{ minHeight:'100vh', display:'grid', placeItems:'center', p:2, background:'radial-gradient(circle at 15% 15%, #dbe7ff 0, transparent 28%), radial-gradient(circle at 85% 80%, #e8dcff 0, transparent 30%), #f7f9fd' }}><Paper elevation={0} sx={{ width:'100%', maxWidth:440, p:{xs:3,sm:5}, border:'1px solid #e6eaf2', borderRadius:4, boxShadow:'0 24px 65px rgba(47, 71, 123, .12)' }}><Box sx={{ width:48,height:48,borderRadius:3,display:'grid',placeItems:'center',bgcolor:'#3061e9',color:'#fff',mb:3 }}><AutoAwesomeRounded /></Box><Typography variant="h4" fontWeight={700}>{title}</Typography><Typography color="text.secondary" mt={1} mb={4}>{subtitle}</Typography>{children}</Paper></Box> }
